language: node_js
node_js:
  - '0.10'
before_script:
  - mysql -uroot -e "create database edgy_test"
  - bower i
  - npm run build
after_success:
  'npm run deploy'

env:
  global:
    - secure: xTMGkIkNB5SAESEkKU+EChYHZqzkr9nOEzl0CP6aITKkT8OklwlKJKKa2jzSxgpUPjzTQub22lK1cBzeN2W5VUFiH+v7YakDx2Nfhk+1gZ/RlSUxy2ROkVecgpVAGcdHqM3in3tVbAdXhcNhGpRe9t/DDTNhk9sdEtllvUFhZC8=
    - secure: QZscFATDEc+YyX9KhWGwAyZ82gG718+6teBrdWJRBKrB9lP+Sjng1AmcYvMY/A04zruvgfbuL81jTC87Uvi9WlEom8g1KAR63zp6JrOsI3NnhDOG9gXYckOSS/DupnvlDv23oMRBOTRk0Z2ginhM/ayVkm5z0sN9s2xyArzVTNk=
    - secure: tDIBUlk/pN1vbqG5bx821WBZZLhJF6VlMPT5iigjA/zRVBcC1zXRPoJrecyUQ1JaUjr/OaN+IPi3bJN9NvSpj/nzEpm1b77svhpIK+5CR01g2CYPUsqY9i/LVQgrLVgt4OJaxR2DGkvIWKeqQUIkMntMhMwcuoUXJPrMTleDzaY=

addons:
  sauce_connect: true